---
title: "inital EDA"
author: "He Guo"
date: "2/7/2020"
output: pdf_document
---

```{r,echo=F,include=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)
library(nnet)
library(rlist)
library(arm)
library(knitr)
# loading packages
```

# Data Cleaning
```{r,echo=F}
bone <- readxl::read_xlsx("BU Thesis Data.xlsx", sheet = 2)
drop<-c()
for (i in 1:nrow(bone))  {
  if (is.na(bone$`Bone Type`[i])){
    drop <- c(drop, i)
  }
}
bone<-bone[-drop,]
# read bone and drop the date without information

# ignore unobserved bone
bone <- dplyr::select(bone,-`Bone Type`,-`Percentage of Feature Present`)
# select columns from Bone Type to Percentage of Feature Present
bone$`Bone Specimen` <- gsub("\\,.*","", bone$`Bone Specimen`)
bone$`Bone Specimen` <- gsub("[^0-9]","", bone$`Bone Specimen`)
bone$`days`<-as.numeric(bone$`Bone Specimen`)
bone<-mutate(bone,`Bone Specimen`=fct_relevel(`Bone Specimen`,'0','30','60','90','180','270','360'))

# creating variable drying day
typeof(bone$`Bone Specimen`)
bone$`Fractographic Features`[bone$`Fractographic Features`=="N/A"]<-"No Feature"
bone$`Fracture Angle`[bone$`Fracture Angle`=="N/A"]<-"non applicable"
bone$`Fracture Type`[bone$`Fracture Type`=="N/A"]<-"non applicable"
bone$`Fracture Surface`[bone$`Fracture Surface`=="N/A"]<-"non applicable"
bone$`Fracture Outline`[bone$`Fracture Outline`=="N/A"]<-"non applicable"
#Clean dependent variable

bone$`Bisecting Fracture`<-factor(bone$`Bisecting Fracture`)
bone$`Fracture-like`<-factor(bone$`Fracture-like`)
bone$`Fracture Angle`<-factor(bone$`Fracture Angle`)
bone$`Fracture Type`<-factor(bone$`Fracture Type`)
bone$`Fracture Surface`<-factor(bone$`Fracture Surface`)
bone$`Fracture Outline`<-factor(bone$`Fracture Outline`)

bone$`Fractographic Features`<-factor(bone$`Fractographic Features`)
# transfer variables to factor 
```
# EDA
```{r}
options(digits = 2) 
table1<-rbind(table(bone$`Bisecting Fracture`,bone$`Bone Specimen`)[2,]/15,table(bone$`Fracture-like`,bone$`Bone Specimen`)[2,]/15)
row.names(table1)<-c('Bisecting percentage','Fracture-like percentage')
kable(table1,caption = 'Bisecting Fracture and Fracture-like percentage for different drying-day groups')




ggplot(data = bone) + geom_bar(mapping = aes(x = `Bone Specimen`, fill = `Fractographic Features`))+labs(x="Drying Days")
ggplot(data = bone, mapping = aes(x = `Bone Specimen`, y = `Number of Fragments`)) + geom_boxplot()+labs(x="Drying Days")

```



# Models
## Bisecting Fracture
```{r}

fit.Bisect_Fracture<-glm(bone$`Bisecting Fracture`~bone$days,family = binomial())
summary(fit.Bisect_Fracture)
binnedplot(fitted(fit.Bisect_Fracture),resid(fit.Bisect_Fracture,type="response"))
```

## Fracture like
```{r}
fit.Fracture_like<-glm(bone$`Fracture-like`~bone$days,family = binomial())
summary(fit.Fracture_like)
binnedplot(fitted(fit.Fracture_like),resid(fit.Fracture_like,type="response"))
```
## Fracture Angle
```{r}
fit.Fracture_Angle<-multinom(bone$`Fracture Angle`~bone$days,trace = FALSE)
summary(fit.Fracture_Angle)
binnedplot(fitted(fit.Fracture_Angle),resid(fit.Fracture_Angle,type="response"))
```

## Number of Fragments
```{r}
fit.Number_of_Fragments <- glm(bone$`Number of Fragments` ~ bone$days, family="poisson")
summary(fit.Number_of_Fragments)
deviance(fit.Number_of_Fragments)/fit.Number_of_Fragments$df.residual
```

## Fracture Type
```{r}
fit.Fracture_Type<-multinom(bone$`Fracture Type`~bone$days,trace = FALSE)
summary(fit.Fracture_Type)
binnedplot(fitted(fit.Fracture_Type),resid(fit.Fracture_Type,type="response"))
```

## Fracture Surface
```{r}
fit.Fracture_Surface<-multinom(bone$`Fracture Surface`~bone$days,trace = FALSE)
summary(fit.Fracture_Surface)
binnedplot(fitted(fit.Fracture_Surface),resid(fit.Fracture_Surface,type="response"))
```

## Fracture Outline
```{r}
fit.Fracture_Outline<-multinom(bone$`Fracture Outline`~bone$days,trace = FALSE)
summary(fit.Fracture_Outline)
binnedplot(fitted(fit.Fracture_Outline),resid(fit.Fracture_Outline,type="response"))

```

## Fractographic Features
```{r}
fit.Fractographic_Features<-multinom(bone$`Fractographic Features`~bone$days,trace = FALSE)
summary(fit.Fractographic_Features)
binnedplot(fitted(fit.Fractographic_Features),resid(fit.Fractographic_Features,type="response"))
```